spring:
  profiles:
    active:
    - local
---
spring:
  application:    name: library-event-producer  profiles:  - local

eureka:  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true    service-url:      default-zone: http://localhost:8761/eureka
  instance:    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  
server:  port: 0
  
learn:  kafka:
    bootstrap-servers:    - localhost:9092    kafka-admin-config:      enabled: true
      topics:      - name: library-events
        partitions: 3
        replicas: 1
    kafka-producer-config:
      enabled: true
      default-topic: library-events
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
      batch-size: 10
      linger-ms: 0